name = "zentrax-backend"
main = "backend/main.py"
compatibility_date = "2026-09-25"
​[vars]
ENVIRONMENT = "production"
​[site]
bucket = "./frontend"
​[observability]
enabled = false
head_sampling_rate = 1
redact_query_string = false
​[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
​[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

